apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tictac-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tictac-app
  template:
    metadata:
      labels:
        app: tictac-app
    spec:
      containers:
        - name: tictac-app
          image: dilipopseng/titacapp
          imagePullPolicy: Always
          ports:
            - containerPort: 80
