name: CI/CD Pipeline

on:
  push:
    branches:
      - test



jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout code from the repo
        uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Install SonarQube Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner.zip -d /opt
          echo "/opt/sonar-scanner-4.6.2.2472-linux/bin" >> $GITHUB_PATH

      - name: Run SonarQube Analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Tictac-App \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # --------------------------
      # Build Image using SHORT SHA
      # --------------------------
      - name: Build Docker Image
        id: build_image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          SHORT_SHA=${COMMIT_SHA::7}
          IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/tictac:$SHORT_SHA"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

          echo "Building Docker image: $IMAGE"
          docker build -t $IMAGE .

      # --------------------------
      # Trivy Scan of Built Image
      # --------------------------
      - name: Scan the Docker Image
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: "${{ env.IMAGE }}"
          format: 'sarif'
          output: 'docker-result.sarif'
          scan-type: image
          ignore-unfixed: false
          vuln-type: os,library
          severity: HIGH,CRITICAL

      - name: Upload Trivy output to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'docker-result.sarif'

      # --------------------------
      # Push Image only when Scan Passes
      # --------------------------
      - name: Push Docker Image
        if: success()
        run: |
          echo "Pushing Image: $IMAGE"
          docker push $IMAGE
