name: CI/CD Pipeline

on:
  push:
    branches:
      - test

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from the repo
        uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Install SonarQube Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner.zip -d /opt
          echo "/opt/sonar-scanner-4.6.2.2472-linux/bin" >> $GITHUB_PATH

      - name: Run SonarQube Analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Tictac-App \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          COMMIT_SHA: ${{ github.sha }}
        run: |
          SHORT_SHA=${COMMIT_SHA::7}
          IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/tictac:$SHORT_SHA"

          echo "Building Docker image: $IMAGE"
          docker build -t $IMAGE .

          echo "Pushing Docker image to ECR..."
          docker push $IMAGE

          echo "Image pushed successfully!"
